
server:
  port: 8080

spring:
  application:
    name: MyMovies
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jnlbp5hqfmbs1xp1.us.auth0.com/

  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1ZjFmZjdkODkxNWJlYjdlMDRlNDk2NTFiZGU0MWI2NCIsIm5iZiI6MTc4MzQyNjM1NC4yMzgwMDAyLCJzdWIiOiI2YTRjZWQzMjZjYjdiNTZkN2FmYjNkYWEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.2uoJkgSrxtnh-KgVV9ssTXyP4A2ffiGmwBtYQByYfFk

jwt:
  secret: d3JpdGUtYW55LXNlY3JldC1rZXktaGVyZS10aGF0LWlzLWxvbmctZW5vdWdo
  expiration-ms: 86400000

auth0:
  audience: https://mymovies-api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true