server:
  port: 8080

spring:
  application:
    name: MyMovies
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jnlbp5hqfmbs1xp1.us.auth0.com/

  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    token: ${TMDB_API_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

auth0:
  audience: https://mymovies-api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true